# Pattern Recognition Model Configuration

model:
  name: "pattern_recognition_v2"
  type: "lstm_attention"
  input_size: 5  # OHLCV
  hidden_size: 128
  num_layers: 2
  num_patterns: 4
  dropout: 0.3

training:
  timeframes:
    - name: "1d"
      epochs: 20
      batch_size: 16
      learning_rate: 0.0005
      min_swing_size: 0.03
    - name: "4h"
      epochs: 15
      batch_size: 24
      learning_rate: 0.0007
      min_swing_size: 0.025
    - name: "1h"
      epochs: 10
      batch_size: 32
      learning_rate: 0.001
      min_swing_size: 0.02
    - name: "15m"
      epochs: 8
      batch_size: 48
      learning_rate: 0.002
      min_swing_size: 0.015
    - name: "5m"
      epochs: 5
      batch_size: 64
      learning_rate: 0.003
      min_swing_size: 0.01

data:
  window_size: 60
  validation_split: 0.2
  shuffle_buffer: 10000

optimization:
  early_stopping_patience: 10
  reduce_lr_patience: 5
  reduce_lr_factor: 0.5
  gradient_clip_val: 1.0

database:
  type: "neon"
  table_prefix: "pattern_recognition"
  checkpoint_frequency: 1  # Save every N epochs 